"""add alarm auto flag

Revision ID: 28338f606740
Revises: 76ce901233aa
Create Date: 2026-06-07 17:34:50.615399
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '28338f606740'
down_revision: str | None = '76ce901233aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_column('auto')

    # ### end Alembic commands ###
