"""initial schema

Revision ID: 76ce901233aa
Revises: 
Create Date: 2026-06-07 16:59:03.756587
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '76ce901233aa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_rules',
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='severity'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apps',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('env', sa.Enum('prod', 'staging', 'dev', name='environment'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('health', sa.Enum('ok', 'warn', 'crit', name='apphealth'), nullable=False),
    sa.Column('composePath', sa.String(length=255), nullable=False),
    sa.Column('gcpProject', sa.String(length=120), nullable=False),
    sa.Column('authMethod', sa.Enum('sa', 'ssh', 'iap', name='authmethod'), nullable=False),
    sa.Column('collectInterval', sa.Integer(), nullable=False),
    sa.Column('credentialRef', sa.String(length=255), nullable=True),
    sa.Column('vmInstance', sa.String(length=120), nullable=False),
    sa.Column('vmZone', sa.String(length=60), nullable=False),
    sa.Column('vmMachine', sa.String(length=60), nullable=True),
    sa.Column('vmIp', sa.String(length=45), nullable=True),
    sa.Column('vmOs', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_name'), ['name'], unique=True)

    op.create_table('notification_channels',
    sa.Column('type', sa.Enum('slack', 'email', 'telegram', 'webhook', 'pagerduty', name='channeltype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_rules',
    sa.Column('condition', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('runCount', sa.Integer(), nullable=False),
    sa.Column('lastRunAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='userrole'), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('containers',
    sa.Column('appId', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serviceType', sa.Enum('fastapi', 'django', 'nginx', 'postgres', 'redis', 'celery', 'flower', 'rabbitmq', 'gunicorn', name='servicetype'), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('running', 'restarting', 'exited', 'paused', name='containerstatus'), nullable=False),
    sa.Column('health', sa.Enum('healthy', 'unhealthy', name='containerhealth'), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('mem', sa.Integer(), nullable=False),
    sa.Column('memLimit', sa.Integer(), nullable=False),
    sa.Column('memPct', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('uptime', sa.String(length=40), nullable=False),
    sa.Column('restarts', sa.Integer(), nullable=False),
    sa.Column('ports', sa.String(length=120), nullable=False),
    sa.Column('exitCode', sa.Integer(), nullable=True),
    sa.Column('exitReason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_appId'), ['appId'], unique=False)
        batch_op.create_index(batch_op.f('ix_containers_name'), ['name'], unique=False)

    op.create_table('alarms',
    sa.Column('appId', sa.String(length=32), nullable=False),
    sa.Column('containerId', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='severity'), nullable=False),
    sa.Column('state', sa.Enum('active', 'acknowledged', 'resolved', name='alarmstate'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('rule', sa.String(length=120), nullable=False),
    sa.Column('triggeredAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledgedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledgedBy', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledgedBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['appId'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['containerId'], ['containers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarms_appId'), ['appId'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alarms_state'), ['state'], unique=False)

    op.create_table('container_actions',
    sa.Column('containerId', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('restart', 'stop', 'start', name='actionkind'), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='actionstatus'), nullable=False),
    sa.Column('requestedBy', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['containerId'], ['containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestedBy'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_actions_containerId'), ['containerId'], unique=False)

    op.create_table('container_logs',
    sa.Column('containerId', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Enum('info', 'warn', 'error', 'fatal', name='loglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recordedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['containerId'], ['containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_logs_containerId'), ['containerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_logs_recordedAt'), ['recordedAt'], unique=False)

    op.create_table('metric_samples',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('containerId', sa.String(length=32), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memPct', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('recordedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['containerId'], ['containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.create_index('ix_metric_container_time', ['containerId', 'recordedAt'], unique=False)

    op.create_table('alarm_events',
    sa.Column('alarmId', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('occurredAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['alarmId'], ['alarms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarm_events_alarmId'), ['alarmId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarm_events_alarmId'))

    op.drop_table('alarm_events')
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_container_time')

    op.drop_table('metric_samples')
    with op.batch_alter_table('container_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_logs_recordedAt'))
        batch_op.drop_index(batch_op.f('ix_container_logs_containerId'))

    op.drop_table('container_logs')
    with op.batch_alter_table('container_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_actions_containerId'))

    op.drop_table('container_actions')
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarms_state'))
        batch_op.drop_index(batch_op.f('ix_alarms_severity'))
        batch_op.drop_index(batch_op.f('ix_alarms_appId'))

    op.drop_table('alarms')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_name'))
        batch_op.drop_index(batch_op.f('ix_containers_appId'))

    op.drop_table('containers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('remediation_rules')
    op.drop_table('notification_channels')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_name'))

    op.drop_table('apps')
    op.drop_table('alarm_rules')
    # ### end Alembic commands ###
